version: '3'
services:
  db:
    image: postgres:15
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo16@2022      
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo16:
    image: odoo:16
    user: root
    depends_on:
      - db
    ports:
      - "10016:8069"
      - "20016:8072" # live chat
    tty: true
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo16@2022
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      # - ./odoo_addons:/usr/lib/python3/dist-packages/odoo/addons/  
      - odoo_payment:/usr/lib/python3/dist-packages/odoo/addons/payment   
      - odoo_website_sales:/usr/lib/python3/dist-packages/odoo/addons/website_sale
    restart: always             # run as a service
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  odoo_payment:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/odoo_payment
  odoo_website_sales:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/odoo_website_sales
    